### ISSUE TITLE
Error: Method is not a base

### ISSUE THREAD

**Issue by shermansmith** [jjv360/nim-termui#1]
When trying to run the example code (using Nim v1.6.0 on a Windows machine) I receive the following error:

```
λ nim c -r termuitest.nim
Hint: used config file 'C:\Users\xxxxx\.choosenim\toolchains\nim-1.6.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\xxxxx\.choosenim\toolchains\nim-1.6.0\config\config.nims' [Conf]
......................................................................................................
C:\Users\xxxxx\.nimble\pkgs\termui-0.1.8\termui\inputfield.nim(9, 7) template/generic instantiation of `class` from here
C:\Users\xxxxx\.nimble\pkgs\termui-0.1.8\termui\inputfield.nim(34, 12) Error: method is not a base
```

I've also tested with Nim v1.4.8 (also on a Windows machine) and receive the same error. Uninstalling and reinstalling the termui package did not fix the issue.

**Comment by jjv360** [comment]
I updated dependencies and pushed version `0.1.9` but I haven't been able to reproduce this... Please reopen this and post your code to reproduce it if it still doesn't work...
